# Kernel makefile for motions sensors
#
# 

obj-$(CONFIG_MPU_SENSORS_MPU9150)	+= mpu9150/
# obj-$(CONFIG_MPU_SENSORS_MPU3050)	+= mpu3050/
# obj-$(CONFIG_SENSORS_AMI603)		+= ami603/ami_sensor/
# obj-$(CONFIG_SENSORS_AMI603_FLIP)	+= ami603/ami_flip/
