/* include/sharp/shterm_k.h
 *
 * Copyright (C) 2010 Sharp Corporation
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef _SHTERM_K_H_
#define _SHTERM_K_H_

#define SHTERM_SUCCESS 0
#define SHTERM_FAILURE 1

#define SHTERM_FLIP_STATE_OPEN 0
#define SHTERM_FLIP_STATE_CLOSE 1

enum {
    SHTERM_INFO_SPEAKER = 0,
    SHTERM_INFO_VIB,
    SHTERM_INFO_CAMERA,
    SHTERM_INFO_LINE,
    SHTERM_INFO_QTV,
    SHTERM_INFO_DTB,
    SHTERM_INFO_LCDPOW,
    SHTERM_INFO_BACKLIGHT,
    SHTERM_INFO_BLUETOOTH,
    SHTERM_INFO_MOBILE_LIGHT,
    SHTERM_INFO_MUSIC,
    SHTERM_INFO_LINE_RINGING,
    SHTERM_INFO_TMM,
    SHTERM_INFO_WLAN_TXRX,
    SHTERM_INFO_SPEAKER_LEV,
    SHTERM_INFO_BACKLIGHT_LEV,
    SHTERM_INFO_IR,
    SHTERM_INFO_SD,
    SHTERM_INFO_GBNAND,
    SHTERM_INFO_USB,
    SHTERM_INFO_WTAP,
    SHTERM_INFO_GPS,
    SHTERM_INFO_ACCELE,
    SHTERM_INFO_COMPS,
    SHTERM_INFO_KEYBACKLIGHT,
    SHTERM_INFO_CTSBACKLIGHT,
    SHTERM_INFO_SUBCAMERA,
    SHTERM_INFO_LMK_S1,
    SHTERM_INFO_LMK_TH1,
    SHTERM_INFO_LMK_TH2,
    SHTERM_INFO_LMK_TH3,
    SHTERM_INFO_GYRO,
    SHTERM_INFO_PEDOMETER,
    SHTERM_INFO_MUSIC_TNL,
    SHTERM_INFO_ALARM,
    SHTERM_INFO_GRIP,
    SHTERM_MAX
};

/* events */
typedef enum {
    SHBATTLOG_EVENT_NONE,
    SHBATTLOG_EVENT_POWER_ON,
    SHBATTLOG_EVENT_ON_INFO,
    SHBATTLOG_EVENT_POWER_OFF,
    SHBATTLOG_EVENT_FATAL_BATT,
    SHBATTLOG_EVENT_BATT_ID_INVALID,

    SHBATTLOG_EVENT_BATT_REPORT_NORM,
    SHBATTLOG_EVENT_BATT_REPORT_CHG,

    SHBATTLOG_EVENT_INDICATER_0,

    SHBATTLOG_EVENT_CHG_INSERT_CHGR,
    SHBATTLOG_EVENT_CHG_REMOVE_CHGR,
    SHBATTLOG_EVENT_CHG_INSERT_USB,
    SHBATTLOG_EVENT_CHG_REMOVE_USB,
    SHBATTLOG_EVENT_CHG_INSERT_MHL,
    SHBATTLOG_EVENT_CHG_REMOVE_MHL,
    SHBATTLOG_EVENT_CHG_PUT_CRADLE,
    SHBATTLOG_EVENT_CHG_REMOVE_CRADLE,
    SHBATTLOG_EVENT_CHG_PUT_WIRELESS,
    SHBATTLOG_EVENT_CHG_REMOVE_WIRELESS,
    SHBATTLOG_EVENT_CHG_INSERT_PROP_CHGR,
    SHBATTLOG_EVENT_CHG_REMOVE_PROP_CHGR,

    SHBATTLOG_EVENT_CHG_END,
    SHBATTLOG_EVENT_CHG_START,
    SHBATTLOG_EVENT_CHG_COMP,
    SHBATTLOG_EVENT_CHG_RESTART,
    SHBATTLOG_EVENT_CHG_ERROR,

    SHBATTLOG_EVENT_CHG_IDLE_ST,
    SHBATTLOG_EVENT_CHG_FAST_ST,
    SHBATTLOG_EVENT_CHG_MAINT_ST,
    SHBATTLOG_EVENT_CHG_HOT_FAST_ST,
    SHBATTLOG_EVENT_CHG_HOT_ADD_FAST_ST,
    SHBATTLOG_EVENT_CHG_ERR_BD_BAT_UNUSUAL_ST,
    SHBATTLOG_EVENT_CHG_ERR_BD_CHG_UNUSUAL_ST,
    SHBATTLOG_EVENT_CHG_ERR_CHG_POWER_SHORTAGE_ST,
    SHBATTLOG_EVENT_CHG_ERR_BAT_ID_INVALID_ST,

    SHBATTLOG_EVENT_CHG_HOT_STOP_ST,
    SHBATTLOG_EVENT_CHG_COLD_STOP_ST,
    SHBATTLOG_EVENT_CHG_MAINT_STOP_ST,
    SHBATTLOG_EVENT_CHG_COUNT_OVER_STOP_ST,

    SHBATTLOG_EVENT_CHGR_OSCILLATION,

    SHBATTLOG_EVENT_FGIC_EX10,
    SHBATTLOG_EVENT_FGIC_EX20,
    SHBATTLOG_EVENT_FGIC_EX30,
    SHBATTLOG_EVENT_FGIC_EX40,
    SHBATTLOG_EVENT_FGIC_EX50,
    SHBATTLOG_EVENT_FGIC_EX60,
    SHBATTLOG_EVENT_FGIC_EX70,
    SHBATTLOG_EVENT_FGIC_EX80,
    SHBATTLOG_EVENT_FGIC_EX90,
    SHBATTLOG_EVENT_FGIC_EX100,

    SHBATTLOG_EVENT_FGIC_NOMAL,
    SHBATTLOG_EVENT_FGIC_INVALID,

    SHBATTLOG_EVENT_OVER_CURRENT1,
    SHBATTLOG_EVENT_OVER_CURR1_DET,
    SHBATTLOG_EVENT_OVER_CURR1_RELEASE,

    SHBATTLOG_EVENT_VOICE_START,
    SHBATTLOG_EVENT_VOICE_END,
    SHBATTLOG_EVENT_DATA_START,
    SHBATTLOG_EVENT_DATA_END,

    SHBATTLOG_EVENT_DVM_REBOOT,
    SHBATTLOG_EVENT_REBOOT,
    SHBATTLOG_EVENT_REBOOT_REASON,
    SHBATTLOG_EVENT_ALLRESET,
    SHBATTLOG_EVENT_CPU_HIGHTEMP_SHUTDOWN,
    SHBATTLOG_EVENT_CLEANUP_REBOOT,

    SHBATTLOG_EVENT_SIM_STATE_ABSENT,
    SHBATTLOG_EVENT_SIM_STATE_NOT_READY,
    SHBATTLOG_EVENT_SIM_STATE_READY,
    SHBATTLOG_EVENT_SIM_STATE_PIN,
    SHBATTLOG_EVENT_SIM_STATE_PUK,
    SHBATTLOG_EVENT_SIM_STATE_NETWORK_PERSONALIZATION,
    SHBATTLOG_EVENT_SIM_STATE_CARD_ERROR,
    SHBATTLOG_EVENT_SIM_STATE_ILLEGAL,
    SHBATTLOG_EVENT_SIM_STATE_CARD_REMOVED,
    SHBATTLOG_EVENT_SIM_STATE_CARD_ADDED,
    SHBATTLOG_EVENT_SIM_STATE_CARD_ERROR_UNKNOWN,
    SHBATTLOG_EVENT_SIM_STATE_CARD_ERROR_POWER_DOWN,
    SHBATTLOG_EVENT_SIM_STATE_CARD_ERROR_POLL_ERROR,
    SHBATTLOG_EVENT_SIM_STATE_CARD_ERROR_VOLT_MISMATCH,
    SHBATTLOG_EVENT_SIM_STATE_CARD_ERROR_PARITY_ERROR,
    SHBATTLOG_EVENT_SIM_STATE_CARD_ERROR_UNKNOWN_REMOVED,
    SHBATTLOG_EVENT_SIM_STATE_CARD_ERROR_CODE_SIM_TECHNICAL_PROBLEMS,

    SHBATTLOG_EVENT_C_AC,
    SHBATTLOG_EVENT_C_HO,
    SHBATTLOG_EVENT_C_DI,
    SHBATTLOG_EVENT_C_AL,
    SHBATTLOG_EVENT_C_IN,
    SHBATTLOG_EVENT_C_WA,
    SHBATTLOG_EVENT_C_AN,
    SHBATTLOG_EVENT_C_EN,

    SHBATTLOG_EVENT_SMT,
    SHBATTLOG_EVENT_SUMT,
    SHBATTLOG_EVENT_SCER,

    SHBATTLOG_EVENT_SDCHKDSK_FATAL_ERR,
    SHBATTLOG_EVENT_SDCHKDSK_NO_MEMORY_ERR,
    SHBATTLOG_EVENT_FMT_GET_DAREA_ERR,
    SHBATTLOG_EVENT_FMT_GET_PAREA_ERR,
    SHBATTLOG_EVENT_FMT_MINSIZE_ERR,
    SHBATTLOG_EVENT_FMT_MAXSIZE_ERR,
    SHBATTLOG_EVENT_FMT_SYS_ERR,

    SHBATTLOG_EVENT_SD_DETECTED,
    SHBATTLOG_EVENT_SD_DETECT_FAILED,
    SHBATTLOG_EVENT_SD_PHY_REMOVED,
    SHBATTLOG_EVENT_SD_SOFT_REMOVED,

    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_UNKNOWN_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_UNKNOWN_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_CMD_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_CMD_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_DATA_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_DATA_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_REQ_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_REQ_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_CMD_CRC_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_CMD_CRC_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_DATA_CRC_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_DATA_CRC_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_OTHER_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_UNKNOWN_OTHER_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_READ_UNKNOWN_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_READ_UNKNOWN_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_READ_CMD_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_READ_CMD_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_READ_DATA_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_READ_DATA_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_READ_REQ_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_READ_REQ_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_READ_CMD_CRC_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_READ_CMD_CRC_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_READ_DATA_CRC_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_READ_DATA_CRC_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_READ_OTHER_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_READ_OTHER_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_UNKNOWN_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_UNKNOWN_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_CMD_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_CMD_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_DATA_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_DATA_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_REQ_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_REQ_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_CMD_CRC_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_CMD_CRC_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_DATA_CRC_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_DATA_CRC_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_OTHER_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_WRITE_OTHER_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_UNKNOWN_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_UNKNOWN_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_CMD_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_CMD_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_DATA_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_DATA_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_REQ_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_REQ_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_CMD_CRC_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_CMD_CRC_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_DATA_CRC_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_DATA_CRC_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_OTHER_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_SECURE_OTHER_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_MISC_UNKNOWN_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_MISC_UNKNOWN_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_MISC_CMD_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_MISC_CMD_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_MISC_DATA_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_MISC_DATA_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_MISC_REQ_TIMEOUT_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_MISC_REQ_TIMEOUT_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_MISC_CMD_CRC_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_MISC_CMD_CRC_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_MISC_DATA_CRC_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_MISC_DATA_CRC_ERROR_RETRY_OUT,
    SHBATTLOG_EVENT_SD_ERROR_MISC_OTHER_ERROR_RECOVERED,
    SHBATTLOG_EVENT_SD_ERROR_MISC_OTHER_ERROR_RETRY_OUT,

    SHBATTLOG_EVENT_SELFCHECK_NG,

    SHBATTLOG_EVENT_SD_INFO,

    SHBATTLOG_EVENT_HOT_STANDBY_ON,
    SHBATTLOG_EVENT_HOT_STANDBY_OFF,

    SHBATTLOG_EVENT_SMT_ENC,
    SHBATTLOG_EVENT_SFMT,
    SHBATTLOG_EVENT_SFMT_ENC,
    SHBATTLOG_EVENT_DATA_ENC,

    SHBATTLOG_EVENT_BATTERY_AUTH_SUCCESS,
    SHBATTLOG_EVENT_BATTERY_AUTH_FAIL,

    SHBATTLOG_EVENT_SHTHERMAL_POWER_OFF_DIALOG,
    SHBATTLOG_EVENT_SHTHERMAL_POWER_OFF,
    SHBATTLOG_EVENT_SHTHERMAL_LCD_RESTRICT,
    SHBATTLOG_EVENT_SHTHERMAL_LCD_RELEASE,

    SHBATTLOG_EVENT_ALLRESET_MDM,
    SHBATTLOG_EVENT_ALLRESET_EXC,

    SHBATTLOG_EVENT_ERROR_CONSUMPTION_HOT_STANDBY_OFF,

    SHBATTLOG_EVENT_INSERT_AUDIO_PLUG,
    SHBATTLOG_EVENT_REMOVE_AUDIO_PLUG,

    SHBATTLOG_EVENT_HOST_MODE_START,
    SHBATTLOG_EVENT_HOST_MODE_END,

    SHBATTLOG_EVENT_QUEUE_FULL,

    SHBATTLOG_EVENT_MAX = 0x7fffffff
} shbattlog_event_num;

typedef struct _shbattlog_info_t {
    int event_num;
    int bat_vol;
    int bat_temp;
    int cpu_temp;
    int chg_temp;
    int cam_temp;
    int pmic_temp;
    int pa_temp;
    int lcd_temp;
    int avg_cur;
    int avg_vol;
    int chg_vol;
    int chg_cur;
    int latest_cur;
    int acc_cur;
    int vol_per;
    int cur_dep_per;
    int avg_dep_per;
#ifdef CONFIG_SHTERM_EMERGENCY
    int tmp_cut;
#endif /* CONFIG_SHTERM_EMERGENCY */
} shbattlog_info_t;

extern int shterm_k_set_info( unsigned long int shterm_info_id, unsigned long int shterm_info_value );

extern int shterm_k_set_event( shbattlog_info_t *info );

extern int shterm_flip_status_set( int state );

extern int shterm_get_music_info( void );

#endif /* _SHTERM_K_H_ */
