#
# Makefile for the FeliCa/NFC drivers.
#
obj-$(CONFIG_SHFELICA) += felica.o
obj-$(CONFIG_SHSNFC)   += snfc.o
obj-$(CONFIG_SHFELICA) += mfcuart.o
obj-$(CONFIG_SHFELICA) += mvdd.o
obj-$(CONFIG_SHFELICA) += clf.o
obj-$(CONFIG_BCM2079X) += clf.o

